# Generated by Django 5.0.1 on 2025-07-24 12:33

import django.core.validators
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_luxury_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=20, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=20, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='propertyconfiguration',
            name='square_footage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
