# Generated by Django 5.0.1 on 2025-07-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_latitude_alter_property_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyconfiguration',
            name='square_footage',
            field=models.PositiveIntegerField(),
        ),
    ]
