# Generated by Django 5.0.1 on 2025-08-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_sharedpropertylist_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('agent', 'Real Estate Agent')], default='viewer', max_length=20),
        ),
    ]
