# Generated by Django 5.0.1 on 2025-08-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpropertylist',
            name='airtable_ids',
            field=models.JSONField(default=0),
        ),
    ]
