# Generated by Django 5.0.1 on 2025-08-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_sharedpropertylist_airtable_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpropertylist',
            name='airtable_ids',
            field=models.JSONField(),
        ),
    ]
