# Generated by Django 5.0.1 on 2025-08-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_sharedpropertylist_airtable_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='image',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='airtable_id',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='brochure',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.URLField(blank=True, default='https://via.placeholder.com/40', null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
