# Generated by Django 5.0.1 on 2025-08-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_remove_propertyimage_image_propertyimage_airtable_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='airtable_id',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
