# Generated by Django 5.0.1 on 2025-08-20 04:48

import django.core.validators
import django.utils.timezone
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_airtable_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtableSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('properties', 'Properties Only'), ('configurations', 'Configurations Only'), ('images', 'Images Only'), ('amenities', 'Amenities Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('properties_processed', models.PositiveIntegerField(default=0)),
                ('configurations_processed', models.PositiveIntegerField(default=0)),
                ('images_processed', models.PositiveIntegerField(default=0)),
                ('amenities_processed', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('files_downloaded', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='property',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this was synced from Airtable', null=True),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='airtable_id',
            field=models.CharField(blank=True, help_text='Airtable record ID for sync purposes', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='description',
            field=models.TextField(blank=True, help_text='Optional amenity description'),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class or name', max_length=50),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertyconfiguration',
            name='airtable_id',
            field=models.CharField(blank=True, help_text='Airtable record ID for sync purposes', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertyconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyconfiguration',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='attachment_index',
            field=models.PositiveIntegerField(default=0, help_text='Index of attachment within Airtable record'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=properties.models.property_image_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='original_record_id',
            field=models.CharField(blank=True, help_text='Original Airtable record ID before splitting', max_length=50),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='airtable_id',
            field=models.CharField(blank=True, help_text='Airtable record ID for sync purposes', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to=properties.models.brochure_path),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='airtable_id',
            field=models.CharField(blank=True, help_text='Airtable record ID for sync purposes', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenity',
            unique_together={('property', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyconfiguration',
            unique_together={('property', 'type')},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['airtable_id'], name='properties__airtabl_5a13ed_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='properties__slug_4fd4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active'], name='properties__is_acti_78cc81_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['luxury_status'], name='properties__luxury__f8ed84_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyamenity',
            index=models.Index(fields=['airtable_id'], name='properties__airtabl_d7e667_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyamenity',
            index=models.Index(fields=['property'], name='properties__propert_4da2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyamenity',
            index=models.Index(fields=['name'], name='properties__name_245344_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyconfiguration',
            index=models.Index(fields=['airtable_id'], name='properties__airtabl_2ae36a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyconfiguration',
            index=models.Index(fields=['property', 'is_available'], name='properties__propert_f43119_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyconfiguration',
            index=models.Index(fields=['bedrooms'], name='properties__bedroom_5b9b63_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyconfiguration',
            index=models.Index(fields=['price'], name='properties__price_1e2f18_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['airtable_id'], name='properties__airtabl_017560_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'order'], name='properties__propert_94c164_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['original_record_id'], name='properties__origina_6f2a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='airtablesynclog',
            index=models.Index(fields=['status'], name='properties__status_9971ed_idx'),
        ),
        migrations.AddIndex(
            model_name='airtablesynclog',
            index=models.Index(fields=['sync_type'], name='properties__sync_ty_6f10f3_idx'),
        ),
        migrations.AddIndex(
            model_name='airtablesynclog',
            index=models.Index(fields=['started_at'], name='properties__started_ab7cf9_idx'),
        ),
    ]
