# Generated by Django 5.0.1 on 2025-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_airtablesynclog_remove_propertyimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpropertylist',
            name='airtable_ids',
            field=models.JSONField(default=list, help_text='List of Airtable record IDs for the properties'),
        ),
    ]
