# Generated by Django 5.0.1 on 2025-08-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_sharedpropertylist_airtable_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
