# Generated by Django 5.0.1 on 2025-08-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='completion_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
